import "server-only";
import crypto from "node:crypto";

/**
 * The one implementation of "a secret that arrives in a link".
 *
 * Two tables now hold one: portal_login_tokens, which signs a customer
 * into the client portal, and signup_invites, which turns a paid checkout
 * into a company and an admin account. Both were carrying their own
 * byte-identical copy of these two functions, and identical copies are
 * exactly the ones that drift silently -- harden one to an HMAC with a
 * server-side pepper and the other keeps its bare digest, with nothing
 * failing to compile and no test going red.
 *
 * The properties both callers depend on, per OWASP's guidance on reset
 * tokens: generated by a cryptographically secure RNG, long enough that
 * guessing is hopeless, and stored only as a digest so that reading the
 * table yields nothing replayable. Single-use and expiry belong to the
 * tables, since only they know what "used" means.
 */

/** 256 bits from the OS CSPRNG, URL-safe so it survives being a query string. */
export function newLinkToken(): string {
  return crypto.randomBytes(32).toString("base64url");
}

/** What goes in the database. The raw token exists only inside the link. */
export function hashLinkToken(raw: string): string {
  return crypto.createHash("sha256").update(raw).digest("hex");
}
